# Generated by Django 5.0.6 on 2024-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreceiver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
